[tool.poetry]
name = "renovate-poetry-python-no-rules"

[tool.poetry.dependencies]
python = ">=3.9.0,<3.10"
django = "==4.2.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
